# Compare unified phrases file created from Basic against the one created from Orchestra
# Intended differences and those caused by bugs are then being removed
# The resulting diff file should be empty

CLASSPATH="/Users/hanno/GitHub/xml-diff-merge/target/diff-merge-1.5.1-SNAPSHOT-jar-with-dependencies.jar"

SOURCE="Phrases"
OLD="Fix$SOURCE.xml"
NEW="$SOURCE.xml"

./splitPhrases.sh $OLD "old" "abbreviations" "AT_" "AT_"
./splitPhrases.sh $NEW "new" "abbreviations" "AT_" "AT_"
./splitPhrases.sh $OLD "old" "categories" "CAT_" "CAT_"
./splitPhrases.sh $NEW "new" "categories" "CAT_" "CAT_"
./splitPhrases.sh $OLD "old" "sections" "SCT_" "SCT_"
./splitPhrases.sh $NEW "new" "sections" "SCT_" "SCT_"
./splitPhrases.sh $OLD "old" "messages" "MSG_" "MSG_.*TITLE"
./splitPhrases.sh $NEW "new" "messages" "MSG_" "MSG_.*TITLE"
./splitPhrases.sh $OLD "old" "msgrefs" "MSG_" "MSG_.*REF_"
./splitPhrases.sh $NEW "new" "msgrefs" "MSG_" "MSG_.*REF_"
./splitPhrases.sh $OLD "old" "components" "COMP_" "COMP_"
./splitPhrases.sh $NEW "new" "components" "COMP_" "COMP_"
./splitPhrases.sh $OLD "old" "comprefs" "CMP_" "CMP_"
./splitPhrases.sh $NEW "new" "comprefs" "CMP_" "CMP_"
./splitPhrases.sh $OLD "old" "fields" "FIELD_" "FIELD_"
./splitPhrases.sh $NEW "new" "fields" "FIELD_" "FIELD_"
./splitPhrases.sh $OLD "old" "enums" "ENUM_" "ENUM_"
./splitPhrases.sh $NEW "new" "enums" "ENUM_" "ENUM_"
./splitPhrases.sh $OLD "old" "datatypes" "DT_" "DT_"
./splitPhrases.sh $NEW "new" "datatypes" "DT_" "DT_"

./comparePhrases.sh "abbreviations" "old" "new"
./comparePhrases.sh "categories" "old" "new"
./comparePhrases.sh "sections" "old" "new"
./comparePhrases.sh "messages" "old" "new"
./comparePhrases.sh "msgrefs" "old" "new"
./comparePhrases.sh "components" "old" "new"
./comparePhrases.sh "comprefs" "old" "new"
./comparePhrases.sh "fields" "old" "new"
./comparePhrases.sh "enums" "old" "new"
./comparePhrases.sh "datatypes" "old" "new"
